version: '3.3'
services: 

  api-test-cedro:
    container_name: api-test-cedro
    image: 'node:12.6-slim'
    command: bash -c "npm i && npm run start:dev"
    working_dir: /app
    restart: unless-stopped
    ports: 
      - 3000:3000
    volumes: 
      - ./:/app